<p>
    <strong>Supported Shortcodes:</strong>
</p>

<ul style="list-style-type:disc;margin-left:20px;">
    <li>Shortcode Example - [cmbd_business showfilter="1"  row_business="3" cats="1" business_ids="1,3,5" ]<br><br>
        <ul>
            <li>showfilter - whether to show the categories filter or not. Value should be 1 or 0</li>
            <li>row_business - number of the business in the row (<code>tiles</code> view only)</li>
            <li>page_business - number of the business on one page</li>
            <li>cats - the id of the catagory from which the business should be displayed</li>
            <li>business_ids - the IDs of the business you only want to show in directory. Value should be an ID, or comma separated IDs.</li>
        </ul>
    </li>

    <li>Business Page shortcodes:<br /><br />
        <ul>

            <li>cmbd_categories - whether to show categories and tags box</li>
            <li>cmbd_post_title - display post title</li>
            <li>cmbd_post_content - display post content</li>
            <li>cmbd_featured_image - display featured image</li>
            <li>cmbd_back_to_index_link - display back link</li>
        </ul>
    </li>
</ul>
